### ISSUE TITLE
DISPLAY=:1 无法更改

### ISSUE THREAD

**Issue by zhiwei-dong** [gezp/docker-ubuntu-desktop#10]
您好，我在ubuntu20宿主机上操作，默认的$DISPLAY为:1, 尝试了很多办法都修改不了这个，另外想问下为什么这里只能:0吗？

**Comment by gezp** [comment]
相关内容你可以参考之前的issue( https://github.com/gezp/docker-ubuntu-desktop/issues/7 )，如果无法改变的这个变量，可以试一下在容器中用使用`vglrun`的时候加上`-d :1.0`参数，例如: 
```bash
vglrun -d :1.0 glxgears
```
但是不保证成功，我没有测试过

**Comment by zhiwei-dong** [comment]
好滴, 感谢
