### ISSUE TITLE
nomachine内无法启动vscode

### ISSUE THREAD

**Issue by zvweaf** [gezp/docker-ubuntu-desktop#11]
大佬，您好，非常感谢您的docker镜像。我现在遇到一个问题，不管我在docker内用chrome下载deb包，还是命令行安装vscode后，都无法打开vscode。app列表里，和终端运行code指令，都无法启动。我在宿主机里已经提前运行xhost +指令，opengl也能正常显示我的显卡。当然vscode通过ssh是可以的。

**Comment by gezp** [comment]
可以运行下面命令进行启动
```bash
code --no-sandbox
```

**Comment by zvweaf** [comment]
可以了可以了，非常感谢
