### ISSUE TITLE
docker commit for any changes in the ubuntu desktop

### ISSUE THREAD

**Issue by darldsla** [gezp/docker-ubuntu-desktop#13]
to commit the changes in the ubuntu desktop after kill / stop the container
`docker kill $(docker ps -q) && docker commit $(docker ps -aq | head -n 1) gezp/ubuntu-desktop`

**Comment by gezp** [comment]
do you have any question? it seems a tip to save container. @darldsla

**Comment by darld** [comment]
@gezp just a suggestion, everything work well for me so far. Thanks for your project.

**Comment by huazai665** [comment]
因为你挂载目录到用户目录下了，刚开始是没有用户的，所以你commit后，再run一个新的容器全是空的
