### ISSUE TITLE
多卡3D渲染

### ISSUE THREAD

**Issue by Young-zq** [gezp/docker-ubuntu-desktop#14]
请问这个怎么支持使用多卡进行3D渲染啊，或者我该如何实现不同的容器分配不同的显卡进行3D渲染呀，感谢感谢！

**Comment by gezp** [comment]
可以参考docker如何分配GPU的，`--gpu all` 改成对应的`gpu id`即可。

**Comment by Young-zq** [comment]
您好，我想问的是如何使用不同的显卡进行VirtualGL的渲染呀，比如我开启多个容器，然后让他们分别使用不同的容器使用不同的显卡进行VirtualGL的渲染。我现在开启多个容器的话在不同的容器中运行vglrun指令，占用的都是同一张卡的资源。谢谢您！

**Comment by Young-zq** [comment]
您好！是的，我对容器指定了不同的GPU，下面这两个分别是启动时指定不同显卡的容器界面，一个可以查询到opengl的信息，一个没有输出。这是opengl的问题吗？谢谢您！
![image](https://github.com/gezp/docker-ubuntu-desktop/assets/49983886/a0a7ad58-6b38-48a6-88e5-3abd836e4b37)

**Comment by gezp** [comment]
我没有试过多卡，但是你可以参考一下另一个项目的解决方法 https://github.com/selkies-project/docker-nvidia-egl-desktop#i-want-to-use-a-specific-gpu-for-opengl-rendering-when-i-have-multiple-gpus-in-one-container

**Comment by Young-zq** [comment]
好的，谢谢您！我去尝试一下
