### ISSUE TITLE
How to open it through Nomachine in a Windows host 

### ISSUE THREAD

**Issue by winnerlyy** [gezp/docker-ubuntu-desktop#15]
I successfully made a container and can viewed ubuntu desktop GUI in my Unbutu host.
But when I tried the same process in Windows 11, nomachine can not find the container's desktop.
I would like to ask how should I fix the problem.
Nomachine server setting in host ubuntu shows nx:// and ssh both, but in host windows nomachine only shows nx:// with no ssh

**Comment by gezp** [comment]
do you mean you tried to run this container in a windows host? @winnerlyy

**Comment by winnerlyy** [comment]
Thank you for your reply, yes I would like run your image on windows 11. But a lot of errors occured, I want to know if that is possible or not

**Comment by gezp** [comment]
I'm sure that this image can be ran on win11, you can access it by ssh or remote desktop,  and OpenGL rendering based on software is still supported. I try to use wsl2 and enable Nvidia GPU for docker on win11, but OpenGL rendering based on Nvidia GPU isn't supported.
