### ISSUE TITLE
docker里面的opengl版本过低怎么办，low version opengl

### ISSUE THREAD

**Issue by gityeezy** [gezp/docker-ubuntu-desktop#19]
我的宿主机opengl版本是4.6，而我用您提供的dockerfile安装的docker-ubuntu20-desktop里的opengl版本是3.1，但是我又不想重新做一个新的镜像和容器来修改opengl版本，怎么将现有的容器提升opengl版本。在这之前，我已经尝试docker run --gpus all或者docker run --device nvidia相关的配置，但都没有效果，请问您是否有好的解决办法。
The opengl version of my host is 4.6, and the opengl version in docker-ubuntu20-desktop I installed using the dockerfile you provided is 3.1, but I don’t want to create a new image and container to modify the opengl version. How can I change the existing opengl version? Some containers upgrade the opengl version. Before this, I have tried the #docker run --gpus all# or #docker run --device nvidiaxxx# commands, but they have no effect. Do you have any good solutions?

**Comment by gezp** [comment]
可以运行`glxinfo | grep -i "opengl"` 看一下容器opengl的信息吗？ 如果你使用nvidia gpu硬件加速，需要在命令前面加上`vglrun`，例如`vglrun glxinfo | grep -i "opengl`.

**Comment by gityeezy** [comment]
![2023-11-24 10-36-14 的屏幕截图](https://github.com/gezp/docker-ubuntu-desktop/assets/115680202/6bb12215-5880-46d2-a627-b8bc7307d21d)
这是我的截图，我代码编译过程中可能涉及到opengl3.2+的版本，但我现在是3.1，编译是不通过的，vglrun也适用于编译过程吗？有没有直接的方法提升版本呢？谢谢

**Comment by gezp** [comment]
我没搞过这个，我也不是很清楚。
