### ISSUE TITLE
Docker容器中vkcube报错，求助

### ISSUE THREAD

**Issue by JonYuanHao** [gezp/docker-ubuntu-desktop#20]
容器创建命令：
docker run -d --restart=on-failure \
    --name my_desktop \
    --cap-add=SYS_PTRACE \
    --gpus all  \
    --shm-size=1024m \
    -p 10022:22  \
    -p 14000:4000  \
    gezp/ubuntu-desktop:20.04-cu11.0.3
执行 vulkaninfo | grep -i "GPU"：
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
		GPU id 	: 0 (NVIDIA GeForce RTX 4090)
		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		GPU id 	: 2 (NVIDIA GeForce RTX 4090)
		GPU id 	: 0 (NVIDIA GeForce RTX 4090)
		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		GPU id 	: 2 (NVIDIA GeForce RTX 4090)
		GPU id 	: 0 (NVIDIA GeForce RTX 4090)
		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		GPU id 	: 2 (NVIDIA GeForce RTX 4090)
GPU id : 0 (NVIDIA GeForce RTX 4090):
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
GPU id : 1 (llvmpipe (LLVM 12.0.0, 256 bits)):
GPU id : 2 (NVIDIA GeForce RTX 4090):
GPU0:
	deviceType     = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
GPU1:
GPU2:
	deviceType     = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
然后执行vkcube时报错：
vkcube: /build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/cube/cube.c:1331: demo_prepare_buffers: Assertion `!err' failed.
Aborted (core dumped)
求助

**Comment by gezp** [comment]
这个问题好像很nvidia驱动有关系，我在使用驱动nvidia-driver-545时复现了该报错，然后我安装了旧的驱动nvidia-driver-525就可以正常运行了。这个问题确实比较奇怪，两个驱动版本下宿主机的vkcube都能正常运行，但是docker内的行为却不一致，具体原因我也不是很清楚。

**Comment by JonYuanHao** [comment]
我驱动是545的，一开始在宿主机里面可以运行vkcube，但后面我export DISPLAY改变了DISPLAY的编号之后，同一个terminal下面运行vkcube报错与docker内一致；服务器是多用户的，更具体的，我在个人普通用户中打开桌面端，进入默认的DISPLAY为：2，此时运行vkcube正常显示结果，然后export DISPLAY=:0，报错与docker内一致，随后我将DISPLAY的值返回来，vkcube再次运行正常。所以有没有可能根本原因不是驱动问题，是X11服务管理器相关的问题，由于我不懂X11，所以更加深入的细节目前也不清楚。
