### ISSUE TITLE
vglrun open3d报错

### ISSUE THREAD

**Issue by AvrilPi** [gezp/docker-ubuntu-desktop#24]
作者你好，我是服务器上使用你的这个docker, `xhost +`会报错`xhost:  unable to open display ""`，但是后面都是没问题的，之后，用nomachin连接，进入图形界面之后
`glxgears` 和`vglrun glxgears `都正常运行，但是我在运行`vglrun open3d draw`时会报错
`[VGL] ERROR: OpenGL error 0x0502 [VGL] ERROR: in createBuffer-- `
我查看容器里$DISPLAY为:1001，我运行`vglrun -d :1001 open3d draw`不会报错但是又没有GPU加速的效果，`vglrun glxgears`是可以正常加速的，我现在不知道怎么用vglrun加速open3d的渲染，请问有什么建议吗

**Comment by gezp** [comment]
我这边也遇到了同样的问题，目前不知道怎么解决，现在这个docker默认是EGL模式，你可以尝试GLX模式创建容器，例如：
```
docker run -d --restart=on-failure \
    --name my_workspace \
    --cap-add=SYS_PTRACE \
    --gpus all  \
    --shm-size=1024m \
    -e VGL_DISPLAY=:0 \
    -p 10022:22  \
    -p 14000:4000  \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    gezp/ubuntu-desktop:20.04-cu11.0.3
```

其中`VGL_DISPLAY`填写你宿主机环境变量`DISPLAY`的值，一般情况下为`:0`。

**Comment by AvrilPi** [comment]
感谢答复，EGL模式和GLX模式是根据是否挂载/tmp/.X11-unix目录决定的吗，如果是这样的话我也尝试过GLX模式，结果还是不能加速open3d

**Comment by gezp** [comment]
> EGL模式和GLX模式是根据是否挂载/tmp/.X11-unix目录决定的吗，

还需要设置环境变量`VGL_DISPLAY`，填写你宿主机环境变量DISPLAY的值，否则vglrun还是默认的EGL模式，GLX模式相当于使用宿主机的桌面环境。

**Comment by AvrilPi** [comment]
不知道是不是因为我用的是无头的服务器，宿主机上没有DISPALY环境变量

**Comment by gezp** [comment]
没显示器吗？如果没有显示器那就不支持GLX模式了，因为GLX模式是相当于使用了宿主机的桌面环境。

**Comment by AvrilPi** [comment]
好的，感谢答复，那我后面加个显示器再试一下看

**Comment by hwfan** [comment]
> 好的，感谢答复，那我后面加个显示器再试一下看

Hi，请问这个issue有进展了吗？我也碰到同样的问题
