### ISSUE TITLE
black screen appears

### ISSUE THREAD

**Issue by gityeezy** [gezp/docker-ubuntu-desktop#32]
Hello, I pulled the images of ubuntu22.04 and ubuntu22.04-cu12.2 and followed your tutorial to make the container. However, when connecting with nomachine, a black screen appears. I have used your other versions before and everything was fine.

**Comment by gezp** [comment]
which os version of your host machine？ @gityeezy

**Comment by gityeezy** [comment]
Linux ye 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gezp** [comment]
it's known bug when use image with tag 22.04 on host ubuntu 20.04，but image with tag 22.04 works well on host ubuntu 22.04，i don't know why.

**Comment by gezp** [comment]
it can be fixed by add flag `--security-opt seccomp=unconfined` when you create container with tag 22.04 on host ubuntu 20.04. like this: 
```bash
docker run -d --restart=on-failure \
    --name my_workspace \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    --gpus all  \
    --shm-size=1024m \
    -e USER=ubuntu \
    -e PASSWORD=ubuntu \
    -e GID=$(id -g) \
    -e UID=$(id -u) \
    -p 10022:22 \
    -p 14000:4000 \
    gezp/ubuntu-desktop:22.04
```

**Comment by gityeezy** [comment]
thank you,it works!!!  :)
