### ISSUE TITLE
有显示器的ubuntu主机上运行黑屏

### ISSUE THREAD

**Issue by huazai665** [gezp/docker-ubuntu-desktop#35]
是不是不能在有显示器主机上运行，我用nomachine连接黑屏，但在wsl上是正常显示的
![image](https://github.com/user-attachments/assets/018f12a1-7491-4352-a529-04e1fa0ba38d)

**Comment by gezp** [comment]
宿主机器系统版本以及使用的镜像是哪一个？可以先看看是不是这个问题https://github.com/gezp/docker-ubuntu-desktop/issues/32

**Comment by huazai665** [comment]
> 宿主机器系统版本以及使用的镜像是哪一个？可以先看看是不是这个问题#32

是的，就是这个问题，按照你的方法可以解决，谢谢
