### ISSUE TITLE
运行habitat-lab进行测试时报错，unable to find CUDA device 0 among 3 EGL devices in total

### ISSUE THREAD

**Issue by huazai665** [gezp/docker-ubuntu-desktop#36]
![image](https://github.com/user-attachments/assets/d0119e2f-a6d6-4faa-bb4e-0e35598e92e5)

**Comment by gezp** [comment]
看样子有点像程序不支持EGL模式，可以尝试GLX模式创建容器，参考https://github.com/gezp/docker-ubuntu-desktop/issues/24#issuecomment-1938011463

**Comment by huazai665** [comment]
谢谢，应该是habitat-lab的问题，他们那边好多人都遇到这个问题了
