### ISSUE TITLE
Kubernates 用deployment加载ubuntu22-cu12.1.1, 无法登录远程登录

### ISSUE THREAD

**Issue by superobk** [gezp/docker-ubuntu-desktop#37]
你好，我们使用kubernetes的deployment加载了镜像ubuntu22-cu12.1.1，创建ubuntu用户和执行./docker_config/entrypoint.sh后。
通过nomachine用ubuntu账号登录出现以下错误：

> 704 704 2024-09-24 04:10:18 595.641 NXSERVER Connected from remote machine '10.233.64.64' using protocol 'NX'.
> Info: Handler started with pid 704 on Tue Sep 24 04:10:18 2024.
> Info: Handling connection from 10.233.64.64 port 64275 on Tue Sep 24 04:10:18 2024.
> 704 704 2024-09-24 04:10:20 216.785 NXSERVER WARNING! Process '/usr/NX/bin/nxexec --isadmin ubuntu' with pid '735/735' finished with exit code 1 after 0,007 seconds.
> 704 704 2024-09-24 04:10:20 217.764 NXSERVER User 'ubuntu' logged in from '10.233.64.64' using authentication method NX-password.
> 103 103 04:10:20 302.753 Redis: 100 changes in 300 seconds. Saving....
> 741 741 2024-09-24 04:10:20 705.669 NXSERVER Connected from remote machine '10.233.64.64' using protocol 'NX'.
> 704 704 2024-09-24 04:10:20 830.853 NXSERVER ERROR! Received error from nxserver --daemon nxFrameBuffer error while starting
> 103 103 2024-09-24 04:10:20 848.293 NXSERVER Previous message repeated 1 time
> 103 103 2024-09-24 04:10:20 848.345 NXSERVER WARNING! Cannot retreive nxnode PID for virtual server BCCC413ED20CEED99EEB417753E332B0.
> 741 741 2024-09-24 04:10:20 848.601 NXSERVER ERROR! Cannot start node to create session
> 103 103 2024-09-24 04:10:20 848.665 NXSERVER WARNING! Process '/usr/NX/bin/nxexec --node --user ubuntu --priority realtime --mode 0 --pid 53' with pid '770/770' finished with exit code 1 after 0,003 seconds.
> Info: Connection from 10.233.64.64 port 64275 closed on Tue Sep 24 04:10:20 2024.
> 741 741 2024-09-24 04:10:20 860.048 HostDescriptorClose: WARNING! Descriptor FD#13 is invalid.
> Info: Handler with pid 704 terminated on Tue Sep 24 04:10:20 2024.
> 704 704 2024-09-24 04:10:20 860.523 NXSERVER Remote machine '10.233.64.64' disconnected.
> 704 704 2024-09-24 04:10:20 866.910 NXSERVER User 'ubuntu' from '10.233.64.64' logged out.
> 704 704 2024-09-24 04:10:20 867.635 NXSERVER Remote machine '10.233.64.64' disconnected.

请问应该如何修改配置解决呢？

**Comment by gezp** [comment]
没看明白，nomachine客户端有报什么错？
