### ISSUE TITLE
NVIDIA显卡限制相关配置存在问题

### ISSUE THREAD

**Issue by utopeadia** [gezp/docker-ubuntu-desktop#38]
容器通过-gpus=‘“device=0,1”’或者NVIDIA-VISXXXXX环境变量限制容器内显卡调用均无效，本地环境经过原生cuda-cudnn-ubuntu容器配置是正常的

**Comment by utopeadia** [comment]
> 这个我也不清楚，没试过

我怀疑是使用的基础镜像有问题，使用英伟达提供的cuda-ubuntu作为基镜像是正常的

**Comment by gezp** [comment]
你的cuda-ubuntu镜像是在哪里？有链接吗？ @utopeadia

**Comment by utopeadia** [comment]
> 你的cuda-ubuntu镜像是在哪里？有链接吗？ @utopeadia

https://hub.docker.com/r/nvidia/cuda
这个，英伟达官方提供的

**Comment by gezp** [comment]
cu系列的镜像就是以这个[cuda](https://hub.docker.com/r/nvidia/cuda)镜像作为基础镜像的啊，不行吗？

**Comment by utopeadia** [comment]
> cu系列的镜像就是以这个[cuda](https://hub.docker.com/r/nvidia/cuda)镜像作为基础镜像的啊，不行吗？

 这就很奇怪了，我这里使用gps=[XXX]指定GPU和修改GPU可见性的环境变量都失效了，进入镜像直接echoNVIDIA VISABLEXXX这个环境变量也是没有输出的，您是一下您那有输出吗。但是在英伟达的镜像下确实是正常

**Comment by utopeadia** [comment]
> 环境变量默认在root用户下，新创建的普通用户的没有生效，最新的镜像应该修复了环境变量这个问题，你可以再试一下

 一会我在GPU服务器更新一下试试看在ubuntu用户下能否正确限制

**Comment by utopeadia** [comment]
> > 环境变量默认在root用户下，新创建的普通用户的没有生效，最新的镜像应该修复了环境变量这个问题，你可以再试一下
> 
> 一会我在GPU服务器更新一下试试看在ubuntu用户下能否正确限制

测试了一下新版本可以的，此贴终结
