### ISSUE TITLE
`20.04-cu11.2`, `20.04-cu11.3`, `20.04-cu11.4` not available

### ISSUE THREAD

**Issue by findmyway** [gezp/docker-ubuntu-desktop#4]
Seems like they are not uploaded to the `aliyuncs`

**Comment by gezp** [comment]
The image tags are incorrect.  you can find all available image tags here https://github.com/gezp/docker-ubuntu-desktop/tags, so you should use `20.04-cu11.2.0` , `20.04-cu11.3.0` , `20.04-cu11.4.0`.

**Comment by findmyway** [comment]
Ah, I see. Thanks!

I thought it should follow the convention in README...
