### ISSUE TITLE
xhost question

### ISSUE THREAD

**Issue by Yeah2333** [gezp/docker-ubuntu-desktop#5]
我们有一个在机房的服务器，已经插上了HDMI欺骗器，然后export display的环境变量。但是执行xhost +时提示
xhost:  unable to open display ":0"，应该怎么做？docker可以正常运行，可以通过ssh访问。和hdmi欺骗器插的显卡有关吗，我们有8张显卡，我随便找了一个插上去了。

**Comment by gezp** [comment]
首先需要声明的一点是，我自己使用的服务器都是安装桌面版的ubuntu系统（Ubuntu Desktop），只是使用hdmi欺骗器代替连接显示器，对于无桌面的ubuntu系统（Ubuntu Server），宿主机没有桌面服务，因此docker也无法利用宿主机的桌面服务。

对于你的情况，我猜测你的服务器可能操作系统本身不提供桌面服务，因此本项目可能不适合你，但是我了解到其它项目可能满足你的需求，其不需要宿主机的桌面服务（换句话说再容器里安装nvidia驱动）
* https://github.com/ColorfulSS/docker-ubuntu-gnome-nomachine

希望这个回答对你有所帮助。
