### ISSUE TITLE
--cap-add=SYS_PTRACE?

### ISSUE THREAD

**Issue by yikomuzi** [gezp/docker-ubuntu-desktop#6]
您好，我发现docker run必须添加--cap-add=SYS_PTRACE nomachine才能连上，有没有办法去掉这条命令？实验室的服务器无法添加--cap-add=SYS_PTRACE

**Comment by gezp** [comment]
不能，这个是必须的，除非你使用`privileged`特权模式，但估计你应该使用不了这个。
