### ISSUE TITLE
VirtualGL Problem

### ISSUE THREAD

**Issue by renhaofan** [gezp/docker-ubuntu-desktop#7]
我是在本地使用你的这个docker，把它当成了类似虚拟机的东西。
本地系统ubuntu20.04, Nvidia Driver Version: 510.60.02    CUDA Version: 11.6.
```
$ xhost +
>>> access control disabled, clients can connect from any host

$ docker run -d --restart=on-failure \
    --name my_workspace \
    --cap-add=SYS_PTRACE \
    --gpus all  \
    --shm-size=1024m \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -p 10022:22  \
    -p 14000:4000  \
    gezp/ubuntu-desktop:20.04-cu11.0
```
之后，用nomachin连接是没有问题的，进入图形界面之后我尝试了
```
$ glxgears
```
也是完全OK的。
但是使用VirtualGL的时候出现了问题， 输入如下命令之后就没有反应了，我可以任意拖动终端，看起来应该是在运行，但是却什么都没有显示。
```
$ vglrun glxgears
```
值得注意的是我本地（容器外）的`${DISPLAY}`为1
```
$ echo ${DISPLAY}
>>> :1
```
之后我尝试了一些办法，比如dicker运行的时候加入` -e DISPLAY=:1`
```
docker run -d --restart=on-failure \
    --name my_workspace \
    --cap-add=SYS_PTRACE \
    --env="QT_X11_NO_MITSHM=1" \
    --gpus all  \
    --shm-size=1024m \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -e DISPLAY=:1 \
    -p 10022:22  \
    -p 14000:4000  \
    gezp/ubuntu-desktop:20.04-cu11.0
```

但是还是没有显示

我之后查看了我本地的两个文件
```
/home/steve/.nx/nxerror.log
/usr/NX/var/log/nxerror.log
```
我发现有以下问题：
```
1279 117188 22:59:11 012.525 ServerNetworkInfoHandler: WARNING! Obtaining network data failed with result -3.
1279 117439 23:01:01 776.566 ServerNetworkInfoHandler: WARNING! Obtaining network data failed with result -7.
1279 1675 23:31:43 029.917 HostWmRunning: WARNING! Giving up after 500 Ms.
/bin/xauth:  file /home/steve/.Xauthority does not exist
1279 122503 23:31:49 092.812 HostWmRunningHelper: WARNING! Failed to open display ':1'.
```
但是不知道如何解决。请问有什么建议么？

**Comment by gezp** [comment]
> 值得注意的是我本地（容器外）的${DISPLAY}为1

我之前也遇到这个问题，目前看来要使用vglrun，${DISPLAY}必须为0，至于你为什么为1，我猜测你的电脑连接了多个显示器，建议你只使用一个显示器试一下（需要重启电脑），再查看${DISPLAY}的值。

**Comment by renhaofan** [comment]
> 

确实连接了多个显示器。 我把显示器HDMI拔掉，重启以后发现${DISPLAY}还是1，我进入容器以后vglrun还是会卡住。我在.zshrc写入`DISPLAY=:0.0 ; export DISPLAY`重启以后，问题还是没有得到解决。

**Comment by renhaofan** [comment]
> > 值得注意的是我本地（容器外）的${DISPLAY}为1
> 
> 我之前也遇到这个问题，目前看来要使用vglrun，${DISPLAY}必须为0，至于你为什么为1，我猜测你的电脑连接了多个显示器，建议你只使用一个显示器试一下（需要重启电脑），再查看${DISPLAY}的值。

确实连接了多个显示器。 我把显示器HDMI拔掉，重启以后发现${DISPLAY}还是1，我进入容器以后vglrun还是会卡住。我在.zshrc写入`DISPLAY=:0.0 ; export DISPLAY`重启以后，问题还是没有得到解决。

**Comment by gezp** [comment]
> 我在.zshrc写入DISPLAY=:0.0 ; export DISPLAY

首先改变这个变量是没有用的，因为一般默认如果只有一个显示器，${DISPLAY}应该为0.0.
你试一下这个方案https://stackoverflow.com/questions/59958148/vglrun-does-not-work-in-a-docker-container.
在容器中`export VGL_DISPLAY=1.0`看有没有效果。

**Comment by renhaofan** [comment]
> 在容器中export VGL_DISPLAY=1.0看有没有效果。

采用了你提到的解决方案以后。
```
ubuntu@8d31469713cb:~$ export VGL_DISPLAY=1.0
ubuntu@8d31469713cb:~$ vglrun glxgears
[VGL] ERROR: Could not open display 1.0.
ubuntu@8d31469713cb:~$ vglrun -d :1.0 glxgears
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris
2184 frames in 5.0 seconds = 436.691 FPS
2452 frames in 5.0 seconds = 490.282 FPS
2986 frames in 5.0 seconds = 597.183 FPS
[VGL] ERROR: in getGLXDrawable--
[VGL]    183: Window has been deleted by window manager
ubuntu@8d31469713cb:~$ glxgears
7785 frames in 5.0 seconds = 1556.961 FPS
X connection to :1002.0 broken (explicit kill or server shutdown).

```
用了vglrun 反而帧率更低了。

我参考了这里https://containerization-automation.readthedocs.io/zh_CN/stable/source/docker/gui/[Docker]GUI%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/#_8

docker启动的时候加入了`--privileged`, 
```
ubuntu@1c9751d566e6:~$ export VGL_DISPLAY=1.0
ubuntu@1c9751d566e6:~$ vglrun glxgears
[VGL] ERROR: Could not open display 1.0.
ubuntu@1c9751d566e6:~$ vglrun -d :1.0 glxgears
10333 frames in 5.0 seconds = 2066.388 FPS
10357 frames in 5.0 seconds = 2071.398 FPS
11088 frames in 5.0 seconds = 2217.374 FPS
11510 frames in 5.0 seconds = 2301.953 FPS
11372 frames in 5.0 seconds = 2274.285 FPS
11791 frames in 5.0 seconds = 2358.200 FPS
[VGL] ERROR: in readback--
[VGL]    261: Window has been deleted by window manager

```
至此问题似乎已经得到了妥善的解决。
还有两个小问题
1. 我在其它地方看到docker 里面vglrun加速大概是百分之45。 我本地运行的话glxgears,大概7000+fps，但是docker vglrun只有2000+ fps, 这个差异是否是docker无法充分利用独显造成的。
2. 关于${DISPLAY}不同 是否是因为驱动安装的问题。我的NVIDIA驱动是通过ppa安装，而非NVIDIA官方.run或者.local安装的驱动。其他机器我发现通过官方安装驱动，并且安装过程勾选了X-config之后。运行`glxinfo | grep OpenGL` 得到的OpenGL version string: 4.6.0 NVIDIA 510.68.02 而我本地同样的结果是4.6 (Compatibility Profile) Mesa 21.2.6.  这个区别会不会同样造成问题1的性能损耗

**Comment by renhaofan** [comment]
又做了一次测试，几乎没有提升
````
ubuntu@1c9751d566e6:~$ glxgears
7821 frames in 5.0 seconds = 1564.155 FPS
8489 frames in 5.0 seconds = 1697.035 FPS
7645 frames in 5.0 seconds = 1528.855 FPS
7485 frames in 5.0 seconds = 1496.661 FPS
8494 frames in 5.0 seconds = 1698.766 FPS
X connection to :1002.0 broken (explicit kill or server shutdown).
ubuntu@1c9751d566e6:~$ vglrun -d :1.0 glxgears
8945 frames in 5.0 seconds = 1788.990 FPS
9760 frames in 5.0 seconds = 1951.896 FPS
9655 frames in 5.0 seconds = 1930.962 FPS
9642 frames in 5.0 seconds = 1928.256 FPS
9048 frames in 5.0 seconds = 1809.578 FPS
[VGL] ERROR: in readback--
[VGL]    261: Window has been deleted by window manager

```

**Comment by gezp** [comment]
> 用了vglrun 反而帧率更低了。
我测试得到了和你类似的结果，但是我也不清楚原因，估计VirtualGL性能就是要比原生OpenGL差一些，毕竟目的只是为了能够在headless主机上运行OpenGL程序。

**Comment by gezp** [comment]
> 用了vglrun 反而帧率更低了。
我测试得到了和你类似的结果，但是我也不清楚原因，估计VirtualGL性能就是要比原生OpenGL差一些，毕竟目的只是为了能够在headless主机上运行OpenGL程序。
